from abc import ABC


class Tree(ABC):
    def _Tree__add_node(self, tree, value): ...
    def _Tree__print_inorder(self, tree): ...
    def _Tree__print_postorder(self, tree): ...
    def _Tree__print_preorder(self, tree): ...
    def _Tree__min_node(self, v): ...
    def _Tree__max_node(self, v): ...
    def _Tree__find(self, v,  value): ...

    def add_node(self, value: object) -> object: ...
    def print_inorder(self) -> None: ...
    def print_postorder(self) -> None: ...
    def print_preorder(self) -> None: ...
    def min_node(self) -> object: ...
    def max_node(self) -> object: ...
    def find(self, value: object) -> bool: ...